### PR TITLE
Make the layout responsive

### PR DESCRIPTION
**Pull request by MarionCouesnon**
Noticeable changes :
- the alignment of the header is now centered
- CTA in mobile version goes directly to EventBrite website instead of the Iframe because of the scrolling bar problem.

### CODE REVIEW

**Comment by MarionCouesnon** [comment]
Here you can see the result : 
screenshot_railgirls-sainte

**Comment by kevcha** [comment]
@mehlah, I let you have a small look on the CSS code, but globaly that's good for me :)

**Comment by mehlah** [comment]
I'll take a look after lunch today.
Question to @MarionCraftsmen : why have you decided to center the header and the footer ?

**Comment by MarionCouesnon** [comment]
I think it's better to center main element as header and footer on a mobile approach. The center alignment makes it more readable and "space-balanced".

**Comment by mehlah** [comment]
LGTM :+1:

Few souvenirs:
railsgirlsste
screen shot 2015-10-12 at 15 54 34

**Pull request merged**
